# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('published_date', models.DateTimeField(null=True, verbose_name='Published date')),
                ('added_date', models.DateTimeField(default=datetime.datetime(2017, 2, 22, 11, 42, 59, 294458, tzinfo=utc), verbose_name='Added date')),
                ('draft', models.BooleanField(default=True, verbose_name='Draft')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posts',
                'verbose_name': 'Post',
            },
        ),
    ]
