# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20170222_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('publication_date', models.DateTimeField(null=True, verbose_name='Publication date')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('draft', models.BooleanField(default=True, verbose_name='Draft')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'entries',
                'verbose_name': 'entry',
                'ordering': ['-publication_date'],
            },
        ),
        migrations.RemoveField(
            model_name='entity',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
