# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170228_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='active',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='draft',
        ),
        migrations.AddField(
            model_name='entry',
            name='end_publication',
            field=models.DateTimeField(blank=True, db_index=True, help_text='End date of publication.', null=True, verbose_name='end publication'),
        ),
        migrations.AddField(
            model_name='entry',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last update'),
        ),
        migrations.AddField(
            model_name='entry',
            name='start_publication',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Start date of publication.', null=True, verbose_name='start publication'),
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'hidden'), (2, 'published')], db_index=True, default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='publication_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text="Used to build the entry's URL.", verbose_name='publication date'),
        ),
    ]
