# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170301_0643'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='entry',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='author',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
